project:
  type: website

website:
  title: "ncbi_searchs"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Reports
      - text: "Introduction"
        href: introduction.qmd
      - section: "Basics"
        href: basics-summary.qmd
        contents:
          - index.qmd
      - section: "Layout"
        contents:
          - layout.qmd
      - section: advanced.qmd
        contents:
          - raw-code.qmd
      - acknowledgment.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



